//
//  DataServices.swift
//  ListProduct
//
//  Created by Максим Гурков on 03.08.2022.
//

import Foundation

class DataServices {
    
   static let shared = DataServices()
    
    let servicesList = [
        Service(nameServices: "Монтаж Арки",
                descriptionServices: "",
                countServices: 1,
                priceServices: 6450),
        Service(nameServices: "Монтаж (Стандарт)",
                descriptionServices: "Подготовка и установка одностворчатой двери",
                countServices: 1,
                priceServices: 5350),
        Service(nameServices: "Монтаж (Нестандарт)",
                descriptionServices: "Подготовка и установка одностворчатой двери не стандартного размера",
                countServices: 1,
                priceServices: 7120),
        Service(nameServices: "Монтаж (Нестандарт плюс)",
                descriptionServices: "Подготовка и установка двестворчатой или раздвижной двери",
                countServices: 1,
                priceServices: 8900),
        Service(nameServices: "Демонтаж",
                descriptionServices: "Демонтаж двери клиента",
                countServices: 1,
                priceServices: 1400),
        Service(nameServices: "Подпил полотна",
                descriptionServices: "Осуществляется подпил полотна мастером на адресе",
                countServices: 1,
                priceServices: 1600),
        Service(nameServices: "Монтаж добора (Стандарт)",
                descriptionServices: "Установка добора до 100мм шириной",
                countServices: 1,
                priceServices: 2900),
        Service(nameServices: "Монтаж добора (Нестандарт)",
                descriptionServices: "Установка добора с выше  100мм шириной",
                countServices: 1,
                priceServices: 4000),
        Service(nameServices: "Установка порога",
                descriptionServices: "Монтаж порога",
                countServices: 1,
                priceServices: 1600),
        Service(nameServices: "Сан-тех панель",
                descriptionServices: "Монтаж сантехнической панели с врезкой под выключатель и розетку (без работ по электрике)",
                countServices: 1,
                priceServices: 2300),
        Service(nameServices: "Увиличение проема по дереву",
                descriptionServices: "",
                countServices: 1,
                priceServices: 2500),
        Service(nameServices: "Увиличение проема по бетону",
                descriptionServices: "",
                countServices: 1,
                priceServices: 3700),
        Service(nameServices: "Врезка замка",
                descriptionServices: "",
                countServices: 1,
                priceServices: 2700),
        Service(nameServices: "Врезка петель",
                descriptionServices: "",
                countServices: 1,
                priceServices: 1300),
        Service(nameServices: "Зашив фрамуги",
                descriptionServices: "Зашив фрамуги гипсокортоном",
                countServices: 1,
                priceServices: 5500),
        Service(nameServices: "Установка наличников",
                descriptionServices: "установка наличников один погонный метр",
                countServices: 1,
                priceServices: 600),
        Service(nameServices: "Установка огранечителя",
                descriptionServices: "Установка дверного огранечителя напольного или настенного",
                countServices: 1,
                priceServices: 900),
        Service(nameServices: "Монтаж антрисоли",
                descriptionServices: "",
                countServices: 1,
                priceServices: 3500),
        Service(nameServices: "Монтаж портала до 100мм",
                descriptionServices: "Монтаж портала в месте с наличниками",
                countServices: 1,
                priceServices: 4000),
        Service(nameServices: "Монтаж портала с выше 100мм",
                descriptionServices: "Монтаж портала в месте с наличниками",
                countServices: 1,
                priceServices: 4900),
        Service(nameServices: "Вынос мусора",
                descriptionServices: "Вынос строительного мусора после монтажа",
                countServices: 1,
                priceServices: 2500),
        Service(nameServices: "Утиль дверей клиента",
                descriptionServices: "Вывоз старых дверей клиента на свалку цена за одну дверь",
                countServices: 1,
                priceServices: 1200),
        Service(nameServices: "Доставка",
                descriptionServices: "Доставка материала по договору",
                countServices: 1,
                priceServices: 2950),
        Service(nameServices: "Подъем стандарт",
                descriptionServices: "Подъем материала до двери клиента на лифте или до второго этажа",
                countServices: 1,
                priceServices: 1000),
        Service(nameServices: "Подъем без лифта стандарт",
                descriptionServices: "Подъем стандартных дверй если лифт не работает либо лифт отсутствует",
                countServices: 1,
                priceServices: 550),
        Service(nameServices: "Подъем без лифта нестандарт",
                descriptionServices: "Подъем нестандартных дверй если лифт не работает либо лифт отсутствует",
                countServices: 1,
                priceServices: 600),
        
        
    ]
    
    private init() {}
    
}
