//
//  DataManagerPogonage.swift
//  ListProduct
//
//  Created by Максим Гурков on 27.07.2022.
//

import Foundation

class DataManagerPogonage {
    
    static let sharet = DataManagerPogonage()
    
    let pogonages = [
        Pogonage(factory: .luxor,
                 material: .ecoShpone,
                 nameDoor: "Короб",
                 dimansion: "",
                 specifications: "",
                 price: 400,
                 flag: false),
        Pogonage(factory: .luxor,
                 material: .ecoShpone,
                 nameDoor: "Наличник",
                 dimansion: "",
                 specifications: "",
                 price: 230,
                 flag: false),
        Pogonage(factory: .luxor,
                 material: .ecoShpone,
                 nameDoor: "Добор 100",
                 dimansion: "",
                 specifications: "",
                 price: 385,
                 flag: false),
        Pogonage(factory: .luxor,
                 material: .ecoShpone,
                 nameDoor: "Добор 150",
                 dimansion: "",
                 specifications: "",
                 price: 460,
                 flag: false),
        Pogonage(factory: .luxor,
                 material: .ecoShpone,
                 nameDoor: "Добор 200",
                 dimansion: "",
                 specifications: "",
                 price: 640,
                 flag: false),
        Pogonage(factory: .luxor,
                 material: .ecoShpone,
                 nameDoor: "Притвор",
                 dimansion: "",
                 specifications: "",
                 price: 440,
                 flag: false),
        Pogonage(factory: .luxor,
                 material: .shpone,
                 nameDoor: "Короб",
                 dimansion: "",
                 specifications: "",
                 price: 500,
                 flag: false),
        Pogonage(factory: .luxor,
                 material: .shpone,
                 nameDoor: "Наличник",
                 dimansion: "",
                 specifications: "",
                 price: 1000,
                 flag: false),
        Pogonage(factory: .luxor,
                 material: .shpone,
                 nameDoor: "Добор 100",
                 dimansion: "",
                 specifications: "",
                 price: 1000,
                 flag: false),
        Pogonage(factory: .luxor,
                 material: .shpone,
                 nameDoor: "Добор 150",
                 dimansion: "",
                 specifications: "",
                 price: 1000,
                 flag: false),
        Pogonage(factory: .luxor,
                 material: .shpone,
                 nameDoor: "Добор 200",
                 dimansion: "",
                 specifications: "",
                 price: 1000,
                 flag: false),
        Pogonage(factory: .luxor,
                 material: .shpone,
                 nameDoor: "Притвор",
                 dimansion: "",
                 specifications: "",
                 price: 1000,
                 flag: false),
        Pogonage(factory: .onyx,
                 material: .shpone,
                 nameDoor: "Короб",
                 dimansion: "",
                 specifications: "",
                 price: 1600,
                 flag: false),
        Pogonage(factory: .onyx,
                 material: .shpone,
                 nameDoor: "Наличник",
                 dimansion: "",
                 specifications: "",
                 price: 1600,
                 flag: false),
        Pogonage(factory: .onyx,
                 material: .shpone,
                 nameDoor: "Добор 100",
                 dimansion: "",
                 specifications: "",
                 price: 1000,
                 flag: false),
        Pogonage(factory: .onyx,
                 material: .shpone,
                 nameDoor: "Добор 150",
                 dimansion: "",
                 specifications: "",
                 price: 1200,
                 flag: false),
        Pogonage(factory: .onyx,
                 material: .shpone,
                 nameDoor: "Добор 200",
                 dimansion: "",
                 specifications: "",
                 price: 1400,
                 flag: false),
        Pogonage(factory: .onyx,
                 material: .shpone,
                 nameDoor: "Притвор",
                 dimansion: "",
                 specifications: "",
                 price: 800,
                 flag: false),
        Pogonage(factory: .tehno,
                 material: .foam,
                 nameDoor: "Пена",
                 dimansion: "",
                 specifications: "",
                 price: 320,
                 flag: false),
        
    ]
    
    private init() {}
}
